#!/bin/bash

function urlescape() {
  PAYLOAD="$1" ruby -rcgi -e "puts CGI.escape(ENV['PAYLOAD'])"
}

if [[ ! -z "${ACG_CONFIG}" ]]; then
  echo "DATABASE_HOST=$DATABASE_HOST"
  echo "DATABASE_PORT=$DATABASE_PORT"
  echo "DATABASE_USER=$DATABASE_USER"
  echo "DATABASE_NAME=$DATABASE_NAME"
  echo "RAILS_PORT=$RAILS_PORT"
  echo "PGSSLMODE=$PGSSLMODE"
else
  export RAILS_PORT=3000
  DATABASE_NAME=catalog_inventory_production
fi

safeuser=$(urlescape ${DATABASE_USER})
safepass=$(urlescape ${DATABASE_PASSWORD})

export RAILS_ENV=production
export DATABASE_URL="postgresql://${safeuser}:${safepass}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?encoding=utf8&pool=5&wait_timeout=5"

exec ${@}
