---
apiVersion: v1
kind: Template
metadata:
  name: catalog-inventory
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: catalog-inventory
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: service
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        env:
        - name: CLOUD_CONNECTOR_URL
          value: ${CLOUD_CONNECTOR_URL}
        - name: SOURCES_URL
          value: ${SOURCES_URL}
        - name: QUEUE_HOST
          value: ${QUEUE_HOST}
        - name: QUEUE_PORT
          value: ${QUEUE_PORT}
        - name: catalog-inventory_LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: catalog-inventory_VALIDTOPICS
          value: ${catalog-inventory_VALIDTOPICS}
        - name: catalog-inventory_URL
          value: ${catalog_inventory_URL}
        - name: CLOWDER_ENABLED
          value: ${CLOWDER_ENABLED}
        - name: INACTIVE_TASK_REMINDER_TIME
          value: ${INACTIVE_TASK_REMINDER_TIME}
        - name: SOURCE_REFRESH_TIMEOUT
          value: ${SOURCE_REFRESH_TIMEOUT}
        readinessProbe:
          tcpSocket:
            port: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: 200m
            memory: 256Mi
    kafkaTopics:
    - replicas: 3
      partitions: 3
      topicName: platform.sources.event-stream
    - replicas: 3
      partitions: 3
      topicName: platform.topological-inventory.operations-ansible-tower
    - replicas: 3
      partitions: 3
      topicName: platform.upload.catalog
    dependencies:
    - ingress
    - sources
    database:
      name: catalog-inventory

parameters:
- name: SOURCES_URL
  value: https://ci.cloud.redhat.com/
- name: QUEUE_HOST
  value: localhost
- name: QUEUE_PORT
  value: "9092"
- name: INACTIVE_TASK_REMINDER_TIME
  value: "30"
- name: SOURCE_REFRESH_TIMEOUT
  value: "10"
- name: catalog-inventory_VALIDTOPICS
  value: event-stream,operations-ansible-tower,catalog
- name: catalog-inventory_URL
  value: http://catalog-inventory:8080/api/v1.0
- name: catalog-inventory_MAXSIZE
  value: '104857600'
- name: LOG_LEVEL
  value: INFO
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 512Mi
- name: MIN_REPLICAS
  value: '1'
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/catalog-inventory
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "true"
- description: ClowdEnv Name
  name: ENV_NAME
  requred: false
